# Settings File
---

# Directory settings for machines
repository:
  remote: 
  loris_local: /home/rohit/hg/sleek_hip/
  local: /Users/rohitmukherjee/dev/repositories/scalaWorkspace/High-Performance-DSLs/Reporting Tool/test_repo/

# Application Settings
app:
  # Time period to run tests in days
  time_period: 180  # Run tests for commits made in the last months
  output_directory_name: Sleek_Test_Results
  # Must end with a '/'
  output_directory_location: /home/rohit/High-Performance-DSLs/Reporting Tool/

# Test specific settings
tests:
  -
   name: sleek tests
   command: sbt run
   directory: /home/rohit/High-Performance-DSLs/
   file_extension: .out
   prefix: sleek_test_
  # Add more tests by following this format:
  #-
  # command: sbt run2
  # directory: /home/rohit/High-Performance-DSLs/
  # file_extension: .out
  # prefix: sleek_test_
